# TODO
# - webservers integration
# - system js packages, jquery, jquery-ui, etc
# - do we need to package .less and not minified .js? nose.cfg?
Summary:	Web-based code review tool
Name:		reviewboard
Version:	1.7.2
Release:	1
License:	MIT
Group:		Applications/Networking
URL:		http://www.review-board.org/
Source0:	http://downloads.reviewboard.org/releases/ReviewBoard/1.7/ReviewBoard-%{version}.tar.gz
# Source0-md5:	f5ead87918a472945384263516dbb06e
Patch0:		default-cache-file-path.patch
BuildRequires:	python-dateutil
BuildRequires:	python-devel
BuildRequires:	python-django-evolution >= 0.6.7
BuildRequires:	python-django-pipeline >= 1.2.22
BuildRequires:	python-djblets >= 0.7.8
BuildRequires:	python-docutils
BuildRequires:	python-markdown >= 2.2.1
BuildRequires:	python-mimeparse
BuildRequires:	python-nose
BuildRequires:	python-paramiko >= 1.7.6
BuildRequires:	python-pygments >= 1.5
BuildRequires:	python-pysvn
BuildRequires:	python-pytz
BuildRequires:	python-recaptcha
BuildRequires:	python-setuptools
BuildRequires:	python-slimit
BuildRequires:	python-sphinx
BuildRequires:	rpmbuild(macros) >= 1.219
BuildRequires:	sed >= 4.0
Requires:	patch
Requires:	patchutils
Requires:	python-PIL
Requires:	python-dateutil
Requires:	python-django >= 1.4.3
Requires:	python-django-evolution >= 0.6.7
Requires:	python-django-pipeline >= 1.2.22
Requires:	python-djblets >= 0.7.1
Requires:	python-docutils
Requires:	python-flup
Requires:	python-markdown >= 2.2.1
Requires:	python-memcached
Requires:	python-mimeparse
Requires:	python-nose
Requires:	python-paramiko >= 1.7.6
Requires:	python-pygments >= 1.5
Requires:	python-pysvn
Requires:	python-pytz
Requires:	python-recaptcha
Requires:	python-slimit
# Pull one of webserver modes
Suggests:	apache-mod_python
Suggests:	apache-mod_wsgi
# Pull in the client libraries for all of the supported databases
Requires:	python-MySQLdb
Requires:	python-psycopg2
Requires:	python-sqlite
# Pull in the tools for working with common repositories
Requires:	git-core
Requires:	mercurial
Requires:	subversion
Obsoletes:	ReviewBoard < 1.7.0
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Review Board is a powerful web-based code review tool that offers
developers an easy way to handle code reviews. It scales well from
small projects to large companies and offers a variety of tools to
take much of the stress and time out of the code review process.

%prep
%setup -q -n ReviewBoard-%{version}
%patch0 -p1

%{__sed} -i -e '1s,^#!.*python,#!%{__python},' reviewboard/manage.py

# Remove packaged egg-info so it's regenerated by setup.py
%{__rm} -r ReviewBoard*.egg-info

%build
%{__python} setup.py build

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT/var/cache/reviewboard/cache
%{__python} setup.py install \
	--skip-build \
	--optimize=2 \
	--root $RPM_BUILD_ROOT

%py_postclean

# scripts that have a shebang and are meaningful to run; make executable:
# need to reinstall as py_postclean has removed .py
install -p reviewboard/manage.py $RPM_BUILD_ROOT%{py_sitescriptdir}/reviewboard/manage.py

# Remove test data from the installed packages
rm -rf $RPM_BUILD_ROOT%{py_sitescriptdir}/reviewboard/diffviewer/testdata \
       $RPM_BUILD_ROOT%{py_sitescriptdir}/reviewboard/scmtools/testdata \
       $RPM_BUILD_ROOT%{py_sitescriptdir}/webtests

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
# The rb-site executable has a PyGTK GUI, so would normally
# require us to ship a .desktop file.  However it can only be run when supplied
# a directory as a command-line argument, hence it wouldn't be meaningful to
# create a .desktop file for it.
%doc AUTHORS COPYING INSTALL NEWS README
%attr(755,root,root) %{_bindir}/rb-site
%attr(755,root,root) %{_bindir}/rbssh
%dir %attr(770,root,http) /var/cache/reviewboard
%dir %attr(770,root,http) /var/cache/reviewboard/cache
%dir %{py_sitescriptdir}/reviewboard
%{py_sitescriptdir}/reviewboard/nose.cfg
%{py_sitescriptdir}/reviewboard/*.py[co]
%attr(755,root,root) %{py_sitescriptdir}/reviewboard/manage.py

%{py_sitescriptdir}/reviewboard/accounts
%{py_sitescriptdir}/reviewboard/admin
%{py_sitescriptdir}/reviewboard/attachments
%{py_sitescriptdir}/reviewboard/changedescs
%{py_sitescriptdir}/reviewboard/cmdline
%{py_sitescriptdir}/reviewboard/diffviewer
%{py_sitescriptdir}/reviewboard/extensions
%{py_sitescriptdir}/reviewboard/hostingsvcs
%{py_sitescriptdir}/reviewboard/htdocs
%{py_sitescriptdir}/reviewboard/notifications
%{py_sitescriptdir}/reviewboard/reviews
%{py_sitescriptdir}/reviewboard/scmtools
%{py_sitescriptdir}/reviewboard/site
%{py_sitescriptdir}/reviewboard/ssh
%{py_sitescriptdir}/reviewboard/templates
%{py_sitescriptdir}/reviewboard/webapi

%dir %{py_sitescriptdir}/reviewboard/static
%dir %{py_sitescriptdir}/reviewboard/static/lib
%dir %{py_sitescriptdir}/reviewboard/static/lib/js
%{py_sitescriptdir}/reviewboard/static/lib/js/backbone-0.9.2.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/csshover2.htc
%dir %{py_sitescriptdir}/reviewboard/static/lib/js/flot
%{py_sitescriptdir}/reviewboard/static/lib/js/flot/excanvas.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/flot/jquery.flot.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/flot/jquery.flot.pie.js
%{py_sitescriptdir}/reviewboard/static/lib/js/flot/jquery.flot.pie.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/flot/jquery.flot.selection.js
%{py_sitescriptdir}/reviewboard/static/lib/js/flot/jquery.flot.selection.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jasmine-1.3.1.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jasmine-html-1.3.1.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jquery-1.8.2.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jquery-ui-1.8.24.custom.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jquery.form.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jquery.masonry.js
%{py_sitescriptdir}/reviewboard/static/lib/js/jquery.timesince.js
%{py_sitescriptdir}/reviewboard/static/lib/js/less-1.3.1.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/pngfix.htc
%{py_sitescriptdir}/reviewboard/static/lib/js/ui.autocomplete.js
%{py_sitescriptdir}/reviewboard/static/lib/js/ui.autocomplete.min.js
%{py_sitescriptdir}/reviewboard/static/lib/js/underscore-1.3.3.min.js
%dir %{py_sitescriptdir}/reviewboard/static/rb
%dir %{py_sitescriptdir}/reviewboard/static/rb/css
%{py_sitescriptdir}/reviewboard/static/rb/css/*.css
%{py_sitescriptdir}/reviewboard/static/rb/css/*.less
%{py_sitescriptdir}/reviewboard/static/rb/images
%dir %{py_sitescriptdir}/reviewboard/static/rb/js
%{py_sitescriptdir}/reviewboard/static/rb/js/*.js
%{py_sitescriptdir}/reviewboard/static/rb/js/models
%{py_sitescriptdir}/reviewboard/static/rb/js/utils
%{py_sitescriptdir}/reviewboard/static/rb/js/views

%if "%{py_ver}" > "2.4"
%{py_sitescriptdir}/ReviewBoard-%{version}-*.egg-info
%endif
